const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  pet: {
    drag: (x, y) => ipcRenderer.send('pet:drag', { x, y }),
    click: () => ipcRenderer.send('pet:click'),
    hide: () => ipcRenderer.send('pet:hide'),
    quit: () => ipcRenderer.send('pet:quit'),
    showMenu: () => ipcRenderer.send('pet:show-menu'),
    resize: (delta) => ipcRenderer.send('pet:resize', delta),
  },
  panel: {
    open: () => ipcRenderer.send('panel:open'),
    close: () => ipcRenderer.send('panel:close'),
    minimize: () => ipcRenderer.send('panel:minimize'),
    drag: (x, y) => ipcRenderer.send('panel:drag', { x, y }),
    setPetSize: (size) => ipcRenderer.send('panel:set-pet-size', size),
    updateShortcuts: (shortcuts) => ipcRenderer.send('shortcuts:update', shortcuts),
  },
  player: {
    play: (trackId) => ipcRenderer.invoke('player:play', trackId),
    pause: () => ipcRenderer.invoke('player:pause'),
    toggle: () => ipcRenderer.invoke('player:toggle'),
    next: () => ipcRenderer.invoke('player:next'),
    prev: () => ipcRenderer.invoke('player:prev'),
    seek: (time) => ipcRenderer.invoke('player:seek', time),
    setVolume: (volume) => ipcRenderer.invoke('player:set-volume', volume),
    toggleMute: () => ipcRenderer.invoke('player:toggle-mute'),
    setMode: (mode) => ipcRenderer.invoke('player:set-mode', mode),
    getState: () => ipcRenderer.invoke('player:get-state'),
    getTrack: () => ipcRenderer.invoke('player:get-track'),
    onTrackChanged: (cb) => ipcRenderer.on('player:track-changed', (e, track) => cb(track)),
    onStateChanged: (cb) => ipcRenderer.on('player:state-changed', (e, state) => cb(state)),
    onVolumeChanged: (cb) => ipcRenderer.on('player:volume-changed', (e, vol) => cb(vol)),
    onRemoteCommand: (cb) => ipcRenderer.on('player:remote-command', (e, cmd) => cb(cmd)),
  },
  scan: {
    addDirectory: (path) => ipcRenderer.invoke('scan:add-directory', path),
    removeDirectory: (path) => ipcRenderer.invoke('scan:remove-directory', path),
    getDirs: () => ipcRenderer.invoke('scan:get-dirs'),
    rescan: () => ipcRenderer.invoke('scan:rescan'),
    onLibraryUpdate: (cb) => ipcRenderer.on('library:update', (e, data) => cb(data)),
  },
  playlist: {
    getAll: () => ipcRenderer.invoke('playlist:get-all'),
    get: (id) => ipcRenderer.invoke('playlist:get', id),
    create: (name) => ipcRenderer.invoke('playlist:create', name),
    update: (playlist) => ipcRenderer.invoke('playlist:update', playlist),
    delete: (id) => ipcRenderer.invoke('playlist:delete', id),
    setTracks: (id, tracks) => ipcRenderer.invoke('playlist:set-tracks', id, tracks),
  },
  config: {
    get: (key) => ipcRenderer.invoke('config:get', key),
    set: (key, value) => ipcRenderer.invoke('config:set', key, value),
  },
  dialog: {
    openDirectory: () => ipcRenderer.invoke('dialog:open-directory'),
    openFiles: () => ipcRenderer.invoke('dialog:open-files'),
  },
  trackInfo: (cb) => ipcRenderer.on('track-info', (e, info) => cb(info)),
  petState: (cb) => ipcRenderer.on('pet:state', (e, state) => cb(state)),
  onPetSizeChanged: (cb) => ipcRenderer.on('pet:size-changed', (e, size) => cb(size)),
  audio: {
    play: (path) => ipcRenderer.send('audio:play', path),
    pause: () => ipcRenderer.send('audio:pause'),
    resume: () => ipcRenderer.send('audio:resume'),
    setVolume: (vol) => ipcRenderer.send('audio:set-volume', vol),
    seek: (time) => ipcRenderer.send('audio:seek', time),
    timeUpdate: (data) => ipcRenderer.send('audio:time-update', data),
    trackEnded: () => ipcRenderer.send('audio:track-ended'),
    onPlay: (cb) => ipcRenderer.on('audio:play', (e, path) => cb(path)),
    onPause: (cb) => ipcRenderer.on('audio:pause', () => cb()),
    onResume: (cb) => ipcRenderer.on('audio:resume', () => cb()),
    onSetVolume: (cb) => ipcRenderer.on('audio:set-volume', (e, vol) => cb(vol)),
    onSeek: (cb) => ipcRenderer.on('audio:seek', (e, time) => cb(time)),
  },
});
